# Generated by Django 5.2.8 on 2025-11-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationanalysis',
            name='accuracy_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='conversationanalysis',
            name='completeness_score',
            field=models.FloatField(default=0.0),
        ),
    ]
